version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.5
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs/app.log:/var/log/app.log:ro
    depends_on:
      - elasticsearch

  fastapi:
    build: .
    container_name: fastapi
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
